### PR TITLE
fix wrong filepath for package.json

### PR DESCRIPTION
**Pull request by dangerousbeans**
was getting `Error: Cannot find module '../../package.json'`

```
> node ./node_modules/vue-gh-pages/index.js

module.js:549
    throw err;
    ^

Error: Cannot find module '../../package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/entropy_vue_truffle/node_modules/.registry.npmjs.org/vue-gh-pages/1.16.3/node_modules/vue-gh-pages/index.js:9:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

### CODE REVIEW

**Comment by KieferSivitz** [comment]
Hey, sorry for the delayed response. I was out of the country for a few weeks. Is this still an issue? When I tested it, it was working properly already. What directory are you calling 'npm run deploy' from?

**Comment by dangerousbeans** [comment]
@KieferSivitz from root directory - is it meant to be run from the /docs dir?

**Comment by KieferSivitz** [comment]
Hm, no, that should be right. I'll look into it tonight to see if I can find out what's going on

**Comment by KieferSivitz** [comment]
The reason they were different was because I was not resolving the paths properly I believe (with path.resolve) so they would work cross-platform. I have also updated the rest of the paths to use path.resolve.

This should all be included in vue-gh-pages 1.18.1, if something is broken let me know

**Pull request merged**
